version: "3.8"

# services
services:
  # server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3001:3001"
      - "6001:6001"
    env_file: ./server/.env
    depends_on:
      - mongodb

  # client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:5173"
      - "5174:5174"
    depends_on:
      - server

  # database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server

    env_file: ./server/.env
#    volumes:
#      - "mongodbdata:/data/db"
